global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using N_Tier.Core.Common;
global using N_Tier.Core.Entities;
global using N_Tier.Shared.Service;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;